[package]
name = "rust-js-numbers"
version = "0.1.0"
authors = ["Rigellute <rigellute@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "rust_js_numbers"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
